export type BugKind =
  | 'compare' // = vs ==, > vs >=
  | 'operator' // wrong arithmetic or logic operator
  | 'off-by-one'
  | 'missing-return'
  | 'indentation'
  | 'wrong-variable'
  | 'syntax'
  | 'type' // mixing text and numbers
  | 'logic';

export const KIND_LABEL: Record<BugKind, string> = {
  compare: 'COMPARISON',
  operator: 'WRONG OPERATOR',
  'off-by-one': 'OFF BY ONE',
  'missing-return': 'MISSING RETURN',
  indentation: 'INDENTATION',
  'wrong-variable': 'WRONG VARIABLE',
  syntax: 'SYNTAX',
  type: 'TYPE MIX-UP',
  logic: 'LOGIC',
};

export interface Snippet {
  id: string;
  level: 1 | 2 | 3;
  kind: BugKind;
  /** What the code is supposed to do, shown above it. */
  goal: string;
  /** 6–12 lines of Python, indented with 4 spaces. */
  code: string[];
  /** Index into `code` of the one buggy line. */
  bug: number;
  /** The corrected version of that line. */
  fix: string;
  why: string;
  /** Python statements that pass with the fix and fail with the bug. Never shown; used by the tests. */
  check: string;
}

export const SNIPPETS: Snippet[] = [
  // ── Level 1 ──────────────────────────────────────────────
  {
    id: 'even',
    level: 1,
    kind: 'compare',
    goal: 'Say whether a number is even.',
    code: ['def is_even(n):', '    if n % 2 = 0:', '        return True', '    else:', '        return False', '', 'print(is_even(4))'],
    bug: 1,
    fix: '    if n % 2 == 0:',
    why: '= stores a value. To compare, Python needs ==.',
    check: 'assert is_even(4) and not is_even(7)',
  },
  {
    id: 'greet',
    level: 1,
    kind: 'syntax',
    goal: 'Greet every name and count them.',
    code: [
      'def greet_all(names):',
      '    count = 0',
      '    for name in names',
      '        print("Hi, " + name)',
      '        count = count + 1',
      '    return count',
    ],
    bug: 2,
    fix: '    for name in names:',
    why: 'A for line must end with a colon.',
    check: 'assert greet_all(["a", "b"]) == 2',
  },
  {
    id: 'area',
    level: 1,
    kind: 'missing-return',
    goal: 'Return the area of a rectangle.',
    code: [
      'def area(width, height):',
      '    result = width * height',
      '',
      'def main():',
      '    a = area(3, 4)',
      '    print("Area:", a)',
      '    return a',
    ],
    bug: 1,
    fix: '    return width * height',
    why: 'area() works out the answer but never returns it, so it gives back None.',
    check: 'assert area(3, 4) == 12',
  },
  {
    id: 'average',
    level: 1,
    kind: 'operator',
    goal: 'Average three test scores.',
    code: [
      'def average(a, b, c):',
      '    total = a + b + c',
      '    avg = total * 3',
      '    return avg',
      '',
      'score = average(90, 80, 70)',
      'print("Average:", score)',
    ],
    bug: 2,
    fix: '    avg = total / 3',
    why: 'An average divides the total by the count. It does not multiply.',
    check: 'assert average(90, 80, 70) == 80',
  },
  {
    id: 'one-to-ten',
    level: 1,
    kind: 'off-by-one',
    goal: 'List the numbers 1 through 10.',
    code: ['def one_to_ten():', '    nums = []', '    for i in range(1, 10):', '        nums.append(i)', '    return nums', '', 'print(one_to_ten())'],
    bug: 2,
    fix: '    for i in range(1, 11):',
    why: 'range() stops BEFORE its end number, so range(1, 10) stops at 9.',
    check: 'assert one_to_ten() == list(range(1, 11))',
  },
  {
    id: 'age',
    level: 1,
    kind: 'compare',
    goal: 'Let someone join if they are 13 or older.',
    code: ['def can_join(age):', '    if age > 13:', '        return True', '    return False', '', 'print(can_join(13))', 'print(can_join(12))'],
    bug: 1,
    fix: '    if age >= 13:',
    why: '> 13 leaves out 13 itself. "13 or older" needs >=.',
    check: 'assert can_join(13) and not can_join(12)',
  },
  {
    id: 'score-msg',
    level: 1,
    kind: 'type',
    goal: "Build a message with the player's score.",
    code: [
      'def score_message(name, score):',
      '    msg = name + " scored " + score',
      '    msg = msg + " points!"',
      '    return msg',
      '',
      'print(score_message("Ana", 42))',
    ],
    bug: 1,
    fix: '    msg = name + " scored " + str(score)',
    why: 'You cannot + text and a number. str() turns the number into text first.',
    check: 'assert score_message("Ana", 42) == "Ana scored 42 points!"',
  },
  {
    id: 'bigger',
    level: 1,
    kind: 'wrong-variable',
    goal: 'Return the larger of two numbers.',
    code: ['def bigger(a, b):', '    if a > b:', '        return a', '    else:', '        return a', '', 'print(bigger(3, 9))'],
    bug: 4,
    fix: '        return b',
    why: 'When a is not bigger, the answer is b. This returns a both times.',
    check: 'assert bigger(3, 9) == 9 and bigger(9, 3) == 9',
  },
  {
    id: 'fahrenheit',
    level: 1,
    kind: 'operator',
    goal: 'Convert Celsius to Fahrenheit.',
    code: [
      'def to_fahrenheit(c):',
      '    f = c * 9 / 5 - 32',
      '    return f',
      '',
      'boiling = to_fahrenheit(100)',
      'print("Water boils at", boiling)',
    ],
    bug: 1,
    fix: '    f = c * 9 / 5 + 32',
    why: 'The formula is F = C × 9/5 + 32. This one subtracts the 32.',
    check: 'assert to_fahrenheit(100) == 212',
  },
  {
    id: 'last-item',
    level: 1,
    kind: 'off-by-one',
    goal: 'Return the last item in a list.',
    code: [
      'def last_item(items):',
      '    n = len(items)',
      '    return items[n]',
      '',
      'colors = ["red", "green", "blue"]',
      'print(last_item(colors))',
    ],
    bug: 2,
    fix: '    return items[n - 1]',
    why: 'Indexes start at 0, so the last item is at len - 1. items[n] is past the end.',
    check: 'assert last_item([1, 2, 3]) == 3',
  },
  {
    id: 'total',
    level: 1,
    kind: 'logic',
    goal: 'Add up all the numbers in a list.',
    code: ['def total(nums):', '    s = 0', '    for n in nums:', '        s = n', '    return s', '', 'print(total([4, 5, 6]))'],
    bug: 3,
    fix: '        s = s + n',
    why: 's = n replaces the running total each time instead of adding to it.',
    check: 'assert total([4, 5, 6]) == 15',
  },
  {
    id: 'vowels',
    level: 1,
    kind: 'logic',
    goal: 'Count the vowels in a word.',
    code: [
      'def count_vowels(word):',
      '    count = 0',
      '    for letter in word:',
      '        if letter in "aeiou":',
      '            count + 1',
      '    return count',
    ],
    bug: 4,
    fix: '            count += 1',
    why: 'count + 1 works out a number and throws it away. count += 1 saves it.',
    check: 'assert count_vowels("banana") == 3',
  },
  {
    id: 'traffic',
    level: 1,
    kind: 'compare',
    goal: 'Say if a traffic light means stop.',
    code: [
      'def must_stop(light):',
      '    if light == "red":',
      '        return True',
      '    elif light = "yellow":',
      '        return True',
      '    return False',
    ],
    bug: 3,
    fix: '    elif light == "yellow":',
    why: 'Comparing needs ==. A single = is a syntax error here.',
    check: 'assert must_stop("yellow") and must_stop("red") and not must_stop("green")',
  },
  {
    id: 'double',
    level: 1,
    kind: 'operator',
    goal: 'Double every number in a list.',
    code: [
      'def double_all(nums):',
      '    result = []',
      '    for n in nums:',
      '        result.append(n * n)',
      '    return result',
      '',
      'print(double_all([1, 2, 3]))',
    ],
    bug: 3,
    fix: '        result.append(n * 2)',
    why: 'n * n squares the number. Doubling is n * 2.',
    check: 'assert double_all([1, 2, 3]) == [2, 4, 6]',
  },
  {
    id: 'countdown',
    level: 1,
    kind: 'off-by-one',
    goal: 'Count down from 5 to 1.',
    code: ['def countdown():', '    out = []', '    for i in range(5, 0, 1):', '        out.append(i)', '    return out', '', 'print(countdown())'],
    bug: 2,
    fix: '    for i in range(5, 0, -1):',
    why: 'To count down, the step must be -1. With +1 the range is empty.',
    check: 'assert countdown() == [5, 4, 3, 2, 1]',
  },

  // ── Level 2 ──────────────────────────────────────────────
  {
    id: 'prices',
    level: 2,
    kind: 'indentation',
    goal: 'Add up all the prices.',
    code: [
      'def total_price(prices):',
      '    total = 0',
      '    for p in prices:',
      '        total += p',
      '        return total',
      '',
      'print(total_price([5, 10, 15]))',
    ],
    bug: 4,
    fix: '    return total',
    why: 'The return is inside the loop, so it quits after the first price.',
    check: 'assert total_price([5, 10, 15]) == 30',
  },
  {
    id: 'weekend',
    level: 2,
    kind: 'operator',
    goal: 'Say if a day is on the weekend.',
    code: [
      'def is_weekend(day):',
      '    if day == "Sat" and day == "Sun":',
      '        return True',
      '    return False',
      '',
      'print(is_weekend("Sat"))',
    ],
    bug: 1,
    fix: '    if day == "Sat" or day == "Sun":',
    why: 'A day cannot be Sat AND Sun at once. It needs or.',
    check: 'assert is_weekend("Sat") and is_weekend("Sun") and not is_weekend("Mon")',
  },
  {
    id: 'first-three',
    level: 2,
    kind: 'off-by-one',
    goal: 'Make a 3-letter city code, like BOS.',
    code: [
      'def first_three(word):',
      '    return word[1:3]',
      '',
      'def short_code(city):',
      '    code = first_three(city)',
      '    return code.upper()',
    ],
    bug: 1,
    fix: '    return word[0:3]',
    why: 'Slices start counting at 0. word[1:3] skips the first letter and keeps only two.',
    check: 'assert short_code("Boston") == "BOS"',
  },
  {
    id: 'largest',
    level: 2,
    kind: 'wrong-variable',
    goal: 'Find the largest number in a list.',
    code: [
      'def largest(nums):',
      '    best = nums[0]',
      '    for n in nums:',
      '        if n > best:',
      '            best = nums',
      '    return best',
    ],
    bug: 4,
    fix: '            best = n',
    why: 'It saves the whole list instead of the number n that just won.',
    check: 'assert largest([3, 9, 2]) == 9',
  },
  {
    id: 'eggs',
    level: 2,
    kind: 'operator',
    goal: 'Count the FULL boxes of 6 eggs.',
    code: ['def full_boxes(eggs):', '    boxes = eggs / 6', '    return boxes', '', 'print(full_boxes(20))', 'print(full_boxes(12))'],
    bug: 1,
    fix: '    boxes = eggs // 6',
    why: '/ gives 3.33 boxes. // divides and drops the leftover: 3 full boxes.',
    check: 'assert full_boxes(20) == 3',
  },
  {
    id: 'grade',
    level: 2,
    kind: 'missing-return',
    goal: 'Give a letter grade.',
    code: [
      'def grade(score):',
      '    if score >= 90:',
      '        return "A"',
      '    elif score >= 80:',
      '        return "B"',
      '    elif score >= 70:',
      '        "C"',
      '    return "F"',
    ],
    bug: 6,
    fix: '        return "C"',
    why: 'A bare "C" does nothing. Without return, a 75 falls through to "F".',
    check: 'assert grade(75) == "C" and grade(95) == "A" and grade(50) == "F"',
  },
  {
    id: 'pin',
    level: 2,
    kind: 'logic',
    goal: 'Check a PIN is exactly 4 digits.',
    code: [
      'def valid_pin(pin):',
      '    if len(pin) != 4:',
      '        return False',
      '    if not pin.isdigit():',
      '        return False',
      '    return False',
    ],
    bug: 5,
    fix: '    return True',
    why: 'Once both checks pass the PIN is good, but this still returns False.',
    check: 'assert valid_pin("1234") and not valid_pin("12a4") and not valid_pin("123")',
  },
  {
    id: 'bonus',
    level: 2,
    kind: 'indentation',
    goal: 'Add a 500 bonus only when the level is complete.',
    code: [
      'def finish(score, complete):',
      '    if complete:',
      '        print("Level complete!")',
      '    score += 500',
      '    return score',
      '',
      'print(finish(100, False))',
    ],
    bug: 3,
    fix: '        score += 500',
    why: 'The bonus line is not indented under the if, so everyone gets it.',
    check: 'assert finish(100, False) == 100 and finish(100, True) == 600',
  },
  {
    id: 'sum-to',
    level: 2,
    kind: 'off-by-one',
    goal: 'Add the numbers from 1 up to n.',
    code: [
      'def sum_to(n):',
      '    total = 0',
      '    i = 1',
      '    while i < n:',
      '        total += i',
      '        i += 1',
      '    return total',
    ],
    bug: 3,
    fix: '    while i <= n:',
    why: 'i < n stops before adding n itself.',
    check: 'assert sum_to(4) == 10',
  },
  {
    id: 'sort',
    level: 2,
    kind: 'logic',
    goal: 'Return the names in A–Z order.',
    code: [
      'def sorted_names(names):',
      '    names = names.sort()',
      '    return names',
      '',
      'roster = ["Zoe", "Al", "Mo"]',
      'print(sorted_names(roster))',
    ],
    bug: 1,
    fix: '    names = sorted(names)',
    why: '.sort() sorts in place and returns None. sorted() returns the new list.',
    check: 'assert sorted_names(["b", "a"]) == ["a", "b"]',
  },
  {
    id: 'word-count',
    level: 2,
    kind: 'logic',
    goal: 'Count how many times each word appears.',
    code: [
      'def word_counts(words):',
      '    counts = {}',
      '    for w in words:',
      '        if w in counts:',
      '            counts[w] += 1',
      '        else:',
      '            counts[w] = 0',
      '    return counts',
    ],
    bug: 6,
    fix: '            counts[w] = 1',
    why: 'The first time a word shows up, it has been seen once, not zero times.',
    check: 'assert word_counts(["a", "b", "a"]) == {"a": 2, "b": 1}',
  },
  {
    id: 'yes',
    level: 2,
    kind: 'compare',
    goal: 'Accept "yes" typed in any capitals.',
    code: [
      'def said_yes(answer):',
      '    answer = answer.strip()',
      '    if answer.lower() == "YES":',
      '        return True',
      '    return False',
      '',
      'print(said_yes(" Yes "))',
    ],
    bug: 2,
    fix: '    if answer.lower() == "yes":',
    why: '.lower() makes everything lowercase, so it can never equal "YES".',
    check: 'assert said_yes(" Yes ") and said_yes("YES") and not said_yes("no")',
  },
  {
    id: 'add-text',
    level: 2,
    kind: 'wrong-variable',
    goal: 'Add two numbers that were typed in as text.',
    code: [
      'def add_text(a, b):',
      '    x = int(a)',
      '    y = int(b)',
      '    total = a + y',
      '    return total',
      '',
      'print(add_text("2", "3"))',
    ],
    bug: 3,
    fix: '    total = x + y',
    why: 'a is still text. The converted number is x.',
    check: 'assert add_text("2", "3") == 5',
  },
  {
    id: 'odds',
    level: 2,
    kind: 'compare',
    goal: 'Keep only the odd numbers.',
    code: [
      'def odds(nums):',
      '    result = []',
      '    for n in nums:',
      '        if n % 2 == 0:',
      '            result.append(n)',
      '    return result',
    ],
    bug: 3,
    fix: '        if n % 2 == 1:',
    why: 'n % 2 == 0 picks the EVEN numbers. Odd numbers leave a remainder of 1.',
    check: 'assert odds([1, 2, 3, 4, 5]) == [1, 3, 5]',
  },
  {
    id: 'positive',
    level: 2,
    kind: 'off-by-one',
    goal: 'Check that every number in the list is positive.',
    code: [
      'def all_positive(nums):',
      '    for i in range(len(nums) - 1):',
      '        if nums[i] <= 0:',
      '            return False',
      '    return True',
      '',
      'print(all_positive([3, 5, -1]))',
    ],
    bug: 1,
    fix: '    for i in range(len(nums)):',
    why: 'range(len - 1) never checks the last number.',
    check: 'assert not all_positive([3, 5, -1]) and all_positive([1, 2])',
  },
  {
    id: 'ticket',
    level: 2,
    kind: 'logic',
    goal: 'Let you in with a ticket, unless you are banned.',
    code: [
      'def can_enter(has_ticket, banned):',
      '    if has_ticket and banned:',
      '        return True',
      '    return False',
      '',
      'print(can_enter(True, False))',
    ],
    bug: 1,
    fix: '    if has_ticket and not banned:',
    why: 'This only lets in banned people. It needs "and not banned".',
    check: 'assert can_enter(True, False) and not can_enter(True, True) and not can_enter(False, False)',
  },

  // ── Level 3 ──────────────────────────────────────────────
  {
    id: 'contains',
    level: 3,
    kind: 'indentation',
    goal: 'Say whether a list contains a target.',
    code: [
      'def contains(items, target):',
      '    for item in items:',
      '        if item == target:',
      '            return True',
      '        return False',
      '',
      'print(contains([1, 2, 3], 3))',
    ],
    bug: 4,
    fix: '    return False',
    why: 'return False is inside the loop, so it gives up after checking only the first item.',
    check: 'assert contains([1, 2, 3], 3) and not contains([1, 2], 5)',
  },
  {
    id: 'factorial',
    level: 3,
    kind: 'logic',
    goal: 'Work out a factorial: 5! = 5×4×3×2×1 = 120.',
    code: ['def factorial(n):', '    if n == 0:', '        return 0', '    return n * factorial(n - 1)', '', 'print(factorial(5))'],
    bug: 2,
    fix: '        return 1',
    why: 'The base case returns 0, and anything times 0 is 0. 0! is 1.',
    check: 'assert factorial(5) == 120 and factorial(0) == 1',
  },
  {
    id: 'shout',
    level: 3,
    kind: 'logic',
    goal: 'Turn a name into a SHOUT, like "ANA!".',
    code: [
      'def shout(name):',
      '    name = name.strip()',
      '    name.upper()',
      '    return name + "!"',
      '',
      'print(shout(" ana "))',
    ],
    bug: 2,
    fix: '    name = name.upper()',
    why: 'Strings never change in place. .upper() returns a new string, which must be saved.',
    check: 'assert shout(" ana ") == "ANA!"',
  },
  {
    id: 'first-negative',
    level: 3,
    kind: 'wrong-variable',
    goal: 'Find the POSITION of the first negative number.',
    code: [
      'def first_negative(nums):',
      '    for i in range(len(nums)):',
      '        if nums[i] < 0:',
      '            return nums[i]',
      '    return -1',
      '',
      'print(first_negative([4, 7, -2, 5]))',
    ],
    bug: 3,
    fix: '            return i',
    why: 'nums[i] is the number itself (-2). The position is i (2).',
    check: 'assert first_negative([4, 7, -2, 5]) == 2 and first_negative([1]) == -1',
  },
  {
    id: 'swap',
    level: 3,
    kind: 'wrong-variable',
    goal: 'Swap the first and last items.',
    code: [
      'def swap_ends(items):',
      '    first = items[0]',
      '    items[0] = items[-1]',
      '    items[-1] = items[0]',
      '    return items',
      '',
      'print(swap_ends([1, 2, 3]))',
    ],
    bug: 3,
    fix: '    items[-1] = first',
    why: 'items[0] was already overwritten. The saved copy in first holds the old value.',
    check: 'assert swap_ends([1, 2, 3]) == [3, 2, 1]',
  },
  {
    id: 'mean',
    level: 3,
    kind: 'wrong-variable',
    goal: 'Average the numbers in a list.',
    code: [
      'def mean(nums):',
      '    total = 0',
      '    for n in nums:',
      '        total += n',
      '    return total / len(total)',
      '',
      'print(mean([2, 4, 6]))',
    ],
    bug: 4,
    fix: '    return total / len(nums)',
    why: 'total is a number and has no length. Divide by how many numbers there are: len(nums).',
    check: 'assert mean([2, 4, 6]) == 4',
  },
  {
    id: 'pairs',
    level: 3,
    kind: 'off-by-one',
    goal: 'Count the pairs of different items that add up to 10.',
    code: [
      'def pairs_to_ten(nums):',
      '    count = 0',
      '    for i in range(len(nums)):',
      '        for j in range(i, len(nums)):',
      '            if nums[i] + nums[j] == 10:',
      '                count += 1',
      '    return count',
    ],
    bug: 3,
    fix: '        for j in range(i + 1, len(nums)):',
    why: 'Starting j at i pairs each item with itself, so a 5 counts as 5 + 5.',
    check: 'assert pairs_to_ten([5, 5, 3, 7]) == 2',
  },
  {
    id: 'reverse',
    level: 3,
    kind: 'logic',
    goal: 'Reverse a word.',
    code: ['def reverse(word):', '    out = ""', '    for ch in word:', '        out = out + ch', '    return out', '', 'print(reverse("python"))'],
    bug: 3,
    fix: '        out = ch + out',
    why: 'Adding each letter to the end rebuilds the word unchanged. Each new letter must go in front.',
    check: 'assert reverse("abc") == "cba"',
  },
  {
    id: 'smallest',
    level: 3,
    kind: 'logic',
    goal: 'Find the smallest number in a list.',
    code: [
      'def smallest(nums):',
      '    best = 0',
      '    for n in nums:',
      '        if n < best:',
      '            best = n',
      '    return best',
      '',
      'print(smallest([7, 3, 9]))',
    ],
    bug: 1,
    fix: '    best = nums[0]',
    why: 'Starting at 0 means no positive number is ever "smaller". Start with a real item.',
    check: 'assert smallest([7, 3, 9]) == 3 and smallest([-2, 5]) == -2',
  },
  {
    id: 'leap',
    level: 3,
    kind: 'logic',
    goal: 'Leap year: divisible by 4, except centuries, unless divisible by 400.',
    code: [
      'def is_leap(year):',
      '    if year % 400 == 0:',
      '        return True',
      '    if year % 100 == 0:',
      '        return True',
      '    return year % 4 == 0',
    ],
    bug: 4,
    fix: '        return False',
    why: 'Centuries like 1900 are NOT leap years (unless divisible by 400).',
    check: 'assert is_leap(2000) and not is_leap(1900) and is_leap(2024) and not is_leap(2023)',
  },
];
