// Hand-written practice items. Every brand detail is illustrative; all phishing domains are fake.
export type ItemKind = 'email' | 'text' | 'url';

export interface PhishItem {
  id: string;
  kind: ItemKind;
  /** Sender (email/text) or where the link was seen (url). */
  from: string;
  subject?: string;
  /** Message text, or the URL itself for kind 'url'. */
  body: string;
  phish: boolean;
  level: 1 | 2 | 3;
  /** Exact substring of from, subject or body that gives it away (or proves it's real). */
  clue: string;
  /** Shown after a mistake. Max 60 characters. */
  why: string;
}

export const ITEMS: PhishItem[] = [
  // ── Level 1: obvious ───────────────────────────────────────────────
  { id: 'l1-amazon-lock', kind: 'email', from: 'security@amaz0n-security.co', subject: 'URGENT: Account locked!!!',
    body: 'Your account will be DELETED in 24 hours. Verify your card now: amaz0n-security.co/verify',
    phish: true, level: 1, clue: 'amaz0n-security.co', why: 'Zero instead of O: a fake Amazon domain.' },
  { id: 'l1-counseling', kind: 'email', from: 'counseling@school.edu', subject: 'Schedule change: period 3',
    body: 'Your period 3 class moved to room 214 starting Monday. No reply needed.',
    phish: false, level: 1, clue: 'No reply needed', why: 'School address, no link, no request. Legit.' },
  { id: 'l1-walmart-win', kind: 'text', from: '+1 (302) 555-0199',
    body: 'CONGRATS! You won a $1000 Walmart gift card! Claim now: bit.ly/fr33-g1ft',
    phish: true, level: 1, clue: 'bit.ly/fr33-g1ft', why: "You didn't enter. Prize + short link = scam." },
  { id: 'l1-mom', kind: 'text', from: 'Mom',
    body: 'Running late, can you start the rice? Home by 6.',
    phish: false, level: 1, clue: 'Home by 6', why: 'Saved contact, normal message, no link.' },
  { id: 'l1-robux', kind: 'url', from: 'Link in a game chat',
    body: 'https://free-robux-generator.xyz/claim',
    phish: true, level: 1, clue: 'free-robux-generator.xyz', why: 'Free currency generators steal accounts.' },
  { id: 'l1-google', kind: 'url', from: 'Typed into the address bar',
    body: 'https://www.google.com/',
    phish: false, level: 1, clue: 'www.google.com', why: 'The real Google domain.' },
  { id: 'l1-netflix-pay', kind: 'email', from: 'billing@netflix-payments-help.com', subject: 'Payment declined',
    body: 'Your membership is on hold. Update payment within 12 hours or lose access.',
    phish: true, level: 1, clue: 'netflix-payments-help.com', why: "Netflix doesn't use netflix-payments-help.com." },
  { id: 'l1-netflix-signin', kind: 'email', from: 'info@account.netflix.com', subject: 'New sign-in to your account',
    body: 'We noticed a new sign-in on a TV in your home. If this was you, you can ignore this email.',
    phish: false, level: 1, clue: 'account.netflix.com', why: 'Real Netflix subdomain, no pressure, no link.' },
  { id: 'l1-usps', kind: 'text', from: '+1 (415) 555-0123',
    body: 'USPS: Your package is held. Pay $1.99 redelivery fee: usps-redeliver.top',
    phish: true, level: 1, clue: 'usps-redeliver.top', why: 'USPS never texts payment links on .top sites.' },
  { id: 'l1-coach', kind: 'text', from: 'Coach Dana',
    body: 'Practice moved to the gym today because of rain. Same time.',
    phish: false, level: 1, clue: 'Same time', why: 'Known contact, no link, nothing asked.' },
  { id: 'l1-school-it', kind: 'email', from: 'helpdesk@schoo1-it.com', subject: 'Password expires today',
    body: 'Keep your school login active. Enter your current password here: schoo1-it.com/keep',
    phish: true, level: 1, clue: 'schoo1-it.com', why: 'A 1 instead of an L, and it asks for a password.' },
  { id: 'l1-library', kind: 'email', from: 'library@school.edu', subject: 'Book due Friday',
    body: '"The Hunger Games" is due Friday. Renew at the front desk.',
    phish: false, level: 1, clue: 'Renew at the front desk', why: 'School sender, no link, nothing risky.' },
  { id: 'l1-insta-badge', kind: 'url', from: 'Link in a DM from a stranger',
    body: 'https://instagram.verify-badge.net/apply',
    phish: true, level: 1, clue: 'verify-badge.net', why: 'The real domain here is verify-badge.net.' },
  { id: 'l1-classroom', kind: 'url', from: 'Link your teacher posted',
    body: 'https://classroom.google.com/c/NjQ1MjM',
    phish: false, level: 1, clue: 'classroom.google.com', why: 'Real Google Classroom domain.' },
  { id: 'l1-giftcard-friend', kind: 'text', from: '+1 (213) 555-0166',
    body: "Hey it's Jordan, lost my phone. Can you buy me a $100 Apple gift card and send the code?",
    phish: true, level: 1, clue: 'send the code', why: 'Gift card codes = cash. Classic scam.' },
  { id: 'l1-spotify', kind: 'email', from: 'no-reply@spotify.com', subject: 'Your receipt',
    body: 'Thanks for your payment of $5.99 for Spotify Premium Student.',
    phish: false, level: 1, clue: 'no-reply@spotify.com', why: 'Real Spotify address, no action needed.' },
  { id: 'l1-lottery', kind: 'email', from: 'claims@intl-lotto-winners.com', subject: 'YOU WON $2,500,000',
    body: 'Send a $50 processing fee to release your prize.',
    phish: true, level: 1, clue: '$50 processing fee', why: 'Real prizes never ask you to pay first.' },
  { id: 'l1-bank-alert', kind: 'text', from: 'Chase',
    body: 'Chase: A $42.10 purchase was made at Target. Not you? Call the number on your card.',
    phish: false, level: 1, clue: 'Call the number on your card', why: 'No link; it sends you to a number you trust.' },
  { id: 'l1-paypa1', kind: 'url', from: 'Link in an email',
    body: 'https://paypa1.com/login',
    phish: true, level: 1, clue: 'paypa1.com', why: 'paypa1 with a 1 is not PayPal.' },
  { id: 'l1-paypal', kind: 'url', from: 'Your saved bookmark',
    body: 'https://www.paypal.com/signin',
    phish: false, level: 1, clue: 'www.paypal.com', why: 'Real PayPal domain from your own bookmark.' },

  // ── Level 2: needs a closer look ──────────────────────────────────
  { id: 'l2-ms365', kind: 'email', from: 'alerts@microsoft365-alerts.com', subject: 'Unusual sign-in activity',
    body: 'We blocked a sign-in from Russia. Review your account: microsoft365-alerts.com/review',
    phish: true, level: 2, clue: 'microsoft365-alerts.com', why: 'Microsoft uses microsoft.com, not this.' },
  { id: 'l2-google-alert', kind: 'email', from: 'no-reply@accounts.google.com', subject: 'Security alert',
    body: 'A new device signed in to your account. Check activity in your Google Account settings.',
    phish: false, level: 2, clue: 'accounts.google.com', why: 'Real Google sender, points you to settings.' },
  { id: 'l2-apple-unlock', kind: 'url', from: 'Link in a text message',
    body: 'https://apple.com-id-unlock.info/login',
    phish: true, level: 2, clue: 'com-id-unlock.info', why: 'The real domain is com-id-unlock.info.' },
  { id: 'l2-closings', kind: 'url', from: 'Link on the school website',
    body: 'https://www.school.edu/closings',
    phish: false, level: 2, clue: 'school.edu', why: "Your school's own domain." },
  { id: 'l2-principal', kind: 'email', from: 'principal.office.school@gmail.com', subject: 'Quick favor',
    body: "I'm in a meeting. I need 5 Google Play gift cards for a staff surprise. Keep this quiet.",
    phish: true, level: 2, clue: 'principal.office.school@gmail.com', why: 'Staff email from Gmail + gift cards = fake.' },
  { id: 'l2-discord-verify', kind: 'email', from: 'noreply@discord.com', subject: 'Verify your email',
    body: "Thanks for signing up! Tap Verify Email to finish. Didn't sign up? Ignore this email.",
    phish: false, level: 2, clue: "Didn't sign up? Ignore this email.", why: 'Expected after signup, real domain, no pressure.' },
  { id: 'l2-wellsfargo-sub', kind: 'url', from: 'Link in an email',
    body: 'https://secure-login.wellsfargo.account-verify.com',
    phish: true, level: 2, clue: 'account-verify.com', why: 'Read right to left: the domain is account-verify.' },
  { id: 'l2-wellsfargo', kind: 'url', from: 'Typed into the address bar',
    body: 'https://www.wellsfargo.com/help/',
    phish: false, level: 2, clue: 'www.wellsfargo.com', why: 'Real bank domain, typed in yourself.' },
  { id: 'l2-steam', kind: 'text', from: 'Discord friend',
    body: 'bro is this you in this video?? steamcommunnity.com/id/clip',
    phish: true, level: 2, clue: 'steamcommunnity.com', why: 'Extra N: steamcommunnity is a fake Steam site.' },
  { id: 'l2-insta-login', kind: 'email', from: 'security@mail.instagram.com', subject: 'New login to Instagram',
    body: 'We noticed a login from Chrome on Windows. If this was you, no action needed. Review it from the Instagram app.',
    phish: false, level: 2, clue: 'from the Instagram app', why: 'Points you to the app, not a link.' },
  { id: 'l2-fedex', kind: 'email', from: 'tracking@fedex-delivery-help.com', subject: 'Delivery attempt failed',
    body: 'Download the attached label to reschedule. Package returned in 48 hours.',
    phish: true, level: 2, clue: 'fedex-delivery-help.com', why: "Not fedex.com, and it's pushing an attachment." },
  { id: 'l2-dentist', kind: 'text', from: 'Bright Smiles Dental',
    body: 'Reminder: cleaning appointment Tue 3:30 PM. Reply C to confirm.',
    phish: false, level: 2, clue: 'Reply C to confirm', why: 'Expected reminder, no link, no info asked.' },
  { id: 'l2-scholarship', kind: 'email', from: 'awards@national-student-grants.org', subject: "You've been selected!",
    body: "You qualify for a $10,000 scholarship you didn't apply for. Pay the $25 application fee today.",
    phish: true, level: 2, clue: '$25 application fee', why: 'Real scholarships never charge to receive.' },
  { id: 'l2-psat', kind: 'email', from: 'noreply@collegeboard.org', subject: 'Your PSAT scores are ready',
    body: 'Sign in to your College Board account to see your scores.',
    phish: false, level: 2, clue: 'collegeboard.org', why: 'Real College Board domain, expected email.' },
  { id: 'l2-qr-parking', kind: 'url', from: 'QR code stuck on a parking meter',
    body: 'https://pay-parking-now.co/meter',
    phish: true, level: 2, clue: 'pay-parking-now.co', why: 'Sticker QR codes on meters steal card numbers.' },
  { id: 'l2-gdoc', kind: 'url', from: 'Link your lab partner sent',
    body: 'https://docs.google.com/document/d/1x9Fq/edit',
    phish: false, level: 2, clue: 'docs.google.com', why: 'Real Google Docs domain from someone you know.' },
  { id: 'l2-wrong-number', kind: 'text', from: '+1 (646) 555-0187',
    body: 'Hi Emily! Are we still on for dinner? Oh sorry, wrong number. You seem nice though!',
    phish: true, level: 2, clue: 'wrong number', why: '"Wrong number" chats lead into scams.' },
  { id: 'l2-discord-code', kind: 'text', from: '43501',
    body: "Your Discord verification code is 482913. Don't share it with anyone.",
    phish: false, level: 2, clue: "Don't share it with anyone", why: 'A code you asked for. Just never share it.' },
  { id: 'l2-roblox', kind: 'email', from: 'events@roblox-rewards.gg', subject: 'Limited event: 10,000 Robux',
    body: 'Log in with your Roblox password to claim before midnight!',
    phish: true, level: 2, clue: 'roblox-rewards.gg', why: 'Not roblox.com, and it wants your password.' },
  { id: 'l2-amazon-ship', kind: 'email', from: 'shipment-tracking@amazon.com', subject: 'Your package has shipped',
    body: 'Your order of "USB-C Cable" is on the way. Track it in Your Orders.',
    phish: false, level: 2, clue: 'shipment-tracking@amazon.com', why: 'Real Amazon address, matches an order.' },

  // ── Level 3: tricky ───────────────────────────────────────────────
  { id: 'l3-ms-co', kind: 'email', from: 'account-security@accountprotection.microsoft.co', subject: 'Microsoft account security code',
    body: 'Someone may have your password. Confirm your identity within 1 hour or your account will be closed.',
    phish: true, level: 3, clue: 'microsoft.co', why: '.co, not .com, plus a 1-hour threat.' },
  { id: 'l3-ms-com', kind: 'email', from: 'account-security-noreply@accountprotection.microsoft.com', subject: 'Microsoft account security code',
    body: 'Your security code is 739204. If you did not request it, you can safely ignore this.',
    phish: false, level: 3, clue: 'accountprotection.microsoft.com', why: 'Real Microsoft domain, no link, no threat.' },
  { id: 'l3-docs-dash', kind: 'email', from: 'Ms. Lee via Google Docs', subject: 'Ms. Lee shared "Final Exam Review"',
    body: 'Open the document: https://docs-google.com/d/exam-review',
    phish: true, level: 3, clue: 'docs-google.com', why: 'Dash, not dot: docs-google.com is fake.' },
  { id: 'l3-docs-real', kind: 'email', from: 'Ms. Lee via Google Docs', subject: 'Ms. Lee shared "Lab Notes"',
    body: 'Open the document: https://docs.google.com/document/d/8hT2/edit',
    phish: false, level: 3, clue: 'docs.google.com', why: 'docs.google.com with a dot is real.' },
  { id: 'l3-paypal-session', kind: 'url', from: 'Link in an email',
    body: 'https://www.paypal.com.secure-session.io/signin',
    phish: true, level: 3, clue: 'secure-session.io', why: 'The domain is secure-session.io, not PayPal.' },
  { id: 'l3-paypal-real', kind: 'url', from: 'Link in the PayPal app',
    body: 'https://www.paypal.com/myaccount/transactions',
    phish: false, level: 3, clue: 'www.paypal.com/', why: 'Ends at paypal.com, then a normal path.' },
  { id: 'l3-punycode', kind: 'url', from: 'Link in a pop-up ad',
    body: 'https://xn--pple-43d.com/id',
    phish: true, level: 3, clue: 'xn--pple-43d.com', why: 'xn-- means lookalike letters: fake "apple".' },
  { id: 'l3-ms-login', kind: 'url', from: "Your school's sign-in page",
    body: 'https://login.microsoftonline.com/',
    phish: false, level: 3, clue: 'login.microsoftonline.com', why: "Microsoft's real school/work sign-in page." },
  { id: 'l3-venmo-call', kind: 'email', from: 'venmo@venmo-support-team.com', subject: 'Payment of $499.00 sent',
    body: 'You sent $499.00 to Alex R. Not you? Call 1-888-555-0143 now to cancel.',
    phish: true, level: 3, clue: 'Call 1-888-555-0143 now', why: 'Fake receipt + phone number = callback scam.' },
  { id: 'l3-venmo-real', kind: 'email', from: 'venmo@venmo.com', subject: 'You paid Sam $12.00',
    body: 'Pizza 🍕. Questions? Open the Venmo app and go to Help.',
    phish: false, level: 3, clue: 'Open the Venmo app', why: 'Real domain, sends you to the app.' },
  { id: 'l3-dropbox', kind: 'email', from: 'no-reply@dropbox.com', subject: 'Taylor shared "Grades.pdf" with you',
    body: 'View file: https://dropbox-share.web.app/grades',
    phish: true, level: 3, clue: 'dropbox-share.web.app', why: 'Real sender look, but the link is web.app.' },
  { id: 'l3-canvas', kind: 'email', from: 'notifications@instructure.com', subject: 'New assignment: Lab 4',
    body: 'Lab 4 is due Friday. View it in Canvas.',
    phish: false, level: 3, clue: 'instructure.com', why: 'Canvas is made by Instructure. Legit.' },
  { id: 'l3-apple-cancel', kind: 'email', from: 'receipts@apple-receipt-cancel.com', subject: 'Your receipt from Apple',
    body: 'Final Cut Pro, $299.99. If you did not make this purchase, cancel here within 24 hours.',
    phish: true, level: 3, clue: 'apple-receipt-cancel.com', why: 'Fake receipt to panic you into clicking.' },
  { id: 'l3-apple-real', kind: 'email', from: 'no_reply@email.apple.com', subject: 'Your receipt from Apple',
    body: 'iCloud+ 50GB, $0.99. Manage subscriptions in Settings on your device.',
    phish: false, level: 3, clue: 'Settings on your device', why: 'Real sender, sends you to Settings.' },
  { id: 'l3-netflix-help', kind: 'url', from: 'Link in a text message',
    body: 'https://netflix.com.restore-access.help/',
    phish: true, level: 3, clue: 'restore-access.help', why: 'The domain is restore-access.help.' },
  { id: 'l3-google-code', kind: 'text', from: '22000',
    body: 'G-662041 is your Google verification code.',
    phish: false, level: 3, clue: 'G-662041', why: 'A code you asked for, no link. Never share it.' },
  { id: 'l3-insta-check', kind: 'email', from: 'security@mail.instagram.com', subject: 'Copyright violation',
    body: 'Your account will be removed for copyright. Appeal: https://instagram-security-check.com',
    phish: true, level: 3, clue: 'instagram-security-check.com', why: 'Sender can be faked. Check the link domain.' },
  { id: 'l3-zoom', kind: 'url', from: 'Link in your class calendar',
    body: 'https://zoom.us/j/93184420571',
    phish: false, level: 3, clue: 'zoom.us', why: "Zoom's real domain is zoom.us." },
  { id: 'l3-nitro', kind: 'text', from: 'Discord friend',
    body: 'free nitro for 3 months!! discord.gift-nitro.com/claim',
    phish: true, level: 3, clue: 'gift-nitro.com', why: 'Real gifts use discord.gift/, not gift-nitro.com.' },
  { id: 'l3-wiki', kind: 'url', from: 'Search result',
    body: 'https://en.wikipedia.org/wiki/Phishing',
    phish: false, level: 3, clue: 'en.wikipedia.org', why: 'The real Wikipedia domain.' },
];
